name: Parse JSON Files

on:
  push:
    branches:
      - main
    paths:
      - 'cmd_sources/**'
  workflow_dispatch:

jobs:
  parse-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install fs path iconv-lite

    - name: Run the script
      run: node sources-meta.js

    - name: Commit and Push changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "Updated sourcesmeta.json"
        add: "sourcesmeta.json"
    - name: Release cmd_sources
      uses: softprops/action-gh-release@0bd7e8b279c9b5b36661d552472fbbfe671fe26e
      with:
        tag_name: "sources-v1"
        files: cmd_sources/*
