name: Update sourcesmeta.json and release cmd_sources

on:
  push:
    branches:
      - main
    paths:
      - 'cmd_sources/**'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  parse-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: files
        if: github.event_name == 'push'
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - name: Export all files in cmd_sources that have added/modified
        if: github.event_name == 'push'
        id: export-files
        run: |
          CHANGED_FILES=$(echo '${{ steps.files.outputs.added_modified }}' | jq -r '.[]' | grep "^cmd_sources/")
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Debug file list
        if: github.event_name == 'push'
        run: |
          echo "Files to release:"
          echo "${{ steps.export-files.outputs.files }}"

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Release cmd_sources
        if: github.event_name == 'push'
        id: release
        uses: softprops/action-gh-release@v4
        with:
          tag_name: "sources-v1"
          files: ${{ steps.export-files.outputs.files }}

      - name: Run the script
        run: |
          npm install fs path iconv-lite
          node sources-meta.js

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated sourcesmeta.json"
          add: "sourcesmeta.json"